# Generated by Django 2.2.5 on 2022-04-02 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220402_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 13, 16, 35, 393580, tzinfo=utc)),
        ),
    ]
